spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:events
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      customer:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        order: 100
        restaurant: 100
        customer: 100
        courier: 100
        customerorder: 100
        courierorder: 100
        restaurantorder: 100